### ISSUE TITLE
Brass Case Sorter

### ISSUE THREAD

**Issue by jadaveon** [sjseth/ArduinoAnnealer#1]
Removed

**Comment by sjseth** [comment]
I emailed direct as well, but sometimes those end up in spam. Here is a copy just in case:


You can email me directly at ***@***.***  If you want more information on the machine, please check out these youtube videos. In the comments there is also a parts list and more information:

https://youtu.be/0o7mW6Ktnkw


https://youtu.be/Tm6WUzW7IRI


https://youtu.be/Z2cLaGn0uKk

Regards,

Seth

________________________________
From: jadaveon ***@***.***>
Sent: Wednesday, April 27, 2022 12:31 PM
To: sjseth/ArduinoAnnealer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sjseth/ArduinoAnnealer] Brass Case Sorter (Issue #1)


Hey there, sorry if this isn't the best mechanism to reach out, but I couldn't find another way to contact you. I'm interested in your brass sorting project. I've begun working on something similar myself and wondered if you wanted to share any details. My email is ***@***.******@***.***>
